### ISSUE TITLE
Node.js v12 is getting deprecated

### ISSUE THREAD

**Issue by Saviq** [DamianReeves/write-file-action#16]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Actions now warn about this:

![obraz](https://user-images.githubusercontent.com/231077/196672530-d1d3fff0-de23-4f7f-a49e-484db960f86a.png)

**Comment by michaelgambold** [comment]
FYI there is an open PR for this that can be found here https://github.com/DamianReeves/write-file-action/pull/15

**Comment by gtwilliams03** [comment]
I think `@actions/core` is at `1.10.0` now which should help with this error.

**Comment by DamianReeves** [comment]
Fixed
