### ISSUE TITLE
`set-output=` command is getting deprecated

### ISSUE THREAD

**Issue by Saviq** [DamianReeves/write-file-action#17]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Actions now warn about this:
![image](https://user-images.githubusercontent.com/231077/196924909-e8c4bc0b-dc5b-4dac-b6d6-c49c2202bf81.png)

**Comment by IFYates** [comment]
Looks like it's used in two places:
1. https://github.com/DamianReeves/write-file-action/blob/e19fd875ed54f16fc583a3486e62547ce4a5dde8/src/index.ts#L29
1. https://github.com/DamianReeves/write-file-action/blob/e19fd875ed54f16fc583a3486e62547ce4a5dde8/src/index.ts#L44

I don't know the purpose of these lines to know if removing them will change the behaviour or what the appropriate replacement would be.

**Comment by gtwilliams03** [comment]
I think `@actions/core` is at `1.10.0` now which should help with this error.

**Comment by DamianReeves** [comment]
Fixed in v1.2
